### ISSUE TITLE
Mixed source for scaffolding

### ISSUE THREAD

**Issue by joriyann** [cezarypiatek/MappingGeneratorReleases#5]
Hi, thanks again for the extension, truly a time savior.

Sometimes I use the object initializer from local variables, it works perfectly for the same name properties. But it leave out the ones it could not match. And I complete by hand. 

Is it possible to have like an hydrid option between local variables and random values. Right now, I can only choose between local variables and random values but I would like to use local variables where it can and fill the remaining properites with random values.

It would save à lot of keystrokes :)

**Comment by cezarypiatek** [comment]
Currently, If you use the "local variables" strategy, unmatched properties are set to `default`.  I'm curios, what are the benefits of using random values instead of `default`?

I can add the option `fallback value generator` that allows to use of a selected generator if there's no match for local variables. What do you think?

![image](https://github.com/cezarypiatek/MappingGeneratorReleases/assets/7759991/3a352987-0e01-45f8-a26c-fc1594c327ea)

**Comment by joriyann** [comment]
Ah right, I didn't see that the advanced scaffolder was previwing the result as I'm using the free version. default is fine with me. But seems not available in the free version. Thanks !
